"""testPrivi test migration

Revision ID: b653eb6060e4
Revises: 00c1aea7a21d
Create Date: 2023-07-25 16:53:18.500755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b653eb6060e4'
down_revision = '00c1aea7a21d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TestPrivilige',
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.alter_column('todo_item', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('todo_item', 'updated_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('todo_list', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('todo_list', 'updated_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('user', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user', 'updated_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'updated_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('todo_list', 'updated_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('todo_list', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('todo_item', 'updated_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('todo_item', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_table('TestPrivilige')
    # ### end Alembic commands ###
